spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&ssl=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 2
      max-wait: 10000
      max-active: 30
      test-on-borrow: true
#
#mybatis:
#  typeAliasesPackage: com.arkr.hene.data.model
#  mapperLocations: classpath:mapper/*.xml

redis:
  cache:
    maxIdle: 4
    maxTotal: 50
    minIdle: 2
    maxWaitMills: 3000
    hostname: localhost
    password: redis123456
    timeout: 3000
    port: 6379
    expiration: 3600